"""empty message

Revision ID: 0902c257cf1a
Revises: a406f7be5985
Create Date: 2024-09-16 10:44:38.339564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0902c257cf1a'
down_revision = 'a406f7be5985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.drop_constraint('list_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('list_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
